// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesChemikalia.Data;

#nullable disable

namespace RazorPagesChemikalia.Migrations
{
    [DbContext(typeof(RazorPagesChemikaliaContext))]
    partial class RazorPagesChemikaliaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RazorPagesChemikalia.Models.Chemikalium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataOdkrycia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ph")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rozpuszczalnosc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StanSkupienia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemperaturaTopnienia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toksycznosc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uzytecznosc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zapach")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Chemikalium");
                });
#pragma warning restore 612, 618
        }
    }
}
